version: '3'

services:
  postgres:
    ports:
      - '5444:5432'
    restart: always
    image: postgres:9.6.5-alpine
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
    network_mode: "host"
  node-app:
    image: baseshop
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - "./:/app"
    working_dir: /app
    ports:
      - "3200:3200"
    depends_on:
      - postgres
    network_mode: "host"


volumes:
  postgres-data:  