version: '3'

services:
  database:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shopbase
    network_mode: "host"
  node-app:
    image: baseshop
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - "./:/app"
    working_dir: /app
    ports:
      - "3200:3200"
    depends_on:
      - database
    network_mode: "host"
volumes:
  database-data:  