version: "3"

networks:
  db-data:
  app-chmp:
    driver: bridge

services:
  db:
    image: postgres:10.4
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shopbase
    networks:
      - app-chmp      
  node-app:
    image: baseshop
    build:
      context: .
      dockerfile: dockerfile
    links:
      - db
    environment:
      NODE_ENV: development
      PORT: 54322
      DB_HOST: db
      DB_USER: user
      DB_PASS: pass
      DATABASE_URL: postgres://user:pass@localhost:54322/shopbase
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3200:3200"
    volumes:
      - "./:/app"
    working_dir: /app
    networks:
      - app-chmp 

volumes:
  db-data: