version: '3'

services:
  postgres:
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    network_mode: "host"
  node-app:
    image: baseshop
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - "./:/app"
    working_dir: /app
    ports:
      - "3200:3200"
    depends_on:
      - postgres
    network_mode: "host"
volumes:    
  postgres-data:  